mix.exs

ExDoc couldn't find package name because it was specified under `docs` and not in the `project` function.

Put package name in correct place in mix.exs

---

lib/telemetry/handler_table.ex

According to public APIs, config should be a `term()`

Fix mismatching typespec

---

mix.exs

When I run `mix test` on the repo, I get the following warning:
```
Warning: the `dialyxir` application's start function was called, which likely means you
did not add the dependency with the `runtime: false` flag. This is not recommended because
it will mean that unnecessary applications are started, and unnecessary applications are most
likely being added to your PLT file, increasing build time.
Please add `runtime: false` in your `mix.exs` dependency section e.g.:
{:dialyxir, "~> 0.5", only: [:dev], runtime: false}
```
This PR simply tells the application to not start dialyxir at runtime so that when running the tests, it won't try to start up the dialyxir application unnecessarily.

Don't run dialyxir at runtime

---

.circleci/config.yml

I guess there is not need to test on both 21.1 and 21.2, so I'd stick to the most recent release of the 21 major version. We need to spare these precious build seconds 😄

Do not run CI builds on OTP 21.1

---

src/telemetry.erl
test/telemetry_SUITE.erl

We're only checking if an event is non-empty when attaching since there are no argument checks in `execute/3`.
Closes #29

Make empty list an invalid event name

---

.circleci/config.yml
CHANGELOG.md
README.md
src/telemetry.erl
src/telemetry.hrl
test/telemetry_SUITE.erl

A single event value has been replaced by a map of measurements. Now it is up to the consumer of the event to decide what part of the payload is important. This is useful in cases where event indicates that a thing happened but there are many properties describing it. 
For example, a database query event may include total time, decode time, wait time and other measurements.

Event measurements

---

src/telemetry.erl

We've done a bunch of testing of Telemetry performance recently. We measured how many iterations of `:telemetry.execute/3` a process is able to run in a given amount of time. Later, we run the same benchmark while increasing the number of processes. Our hypothesis was that *n* processes would perform *n* times iterations of a single process (so if one process did 100 iterations, two processes would do 200) for *n* smaller than the number of schedulers, and for *n* greater than or equal to the number of iterations would be constant.
However, after running a bunch of tests, it turned out that it's not the case (the machine has4 physical cores):
The X axis is the number of processes, and the Y axis is the ratio of number of iterations to the number of iterations performed by a single …

Mention performance impact of using function captures

---

README.md

- Make clear that the first argument is a handler id that must be unique
- Show matching on the ok atom return value so that duplicate ids do not
cause a silent failure
- Format the code examples across multiple lines so that scrolling isn't
necessary
- Add another link to the detailed documentation

Make README examples more "foolproof"

---

src/telemetry.erl

This reduces confusion as it is more important for user that use `telemetry:attach/4` to know where the callback will run rather than to know the event provider to know.

Move running process information to the attach functions

---

src/telemetry.erl
src/telemetry.hrl
src/telemetry_handler_table.erl
test/telemetry_SUITE.erl

This PR wraps the calls to `telemetry:execute` to protect against crashes if the `telemetry` app hasn't started & the ETS tables don't exist.
I haven't written much erlang so all feedback is welcome
fixes #53

Protect calls to execute

---

README.md

I wrote an event handler for a span and was surprised by the results in the duration field. I hadn't worked with native units before, and wanted to provide a little more context on how you might use them.

add a note about using convert_time_unit

---

src/telemetry.erl
test/telemetry_SUITE.erl

This adds support for span contexts so that tracing libraries can correlate unique event executions within a process for the same span. A default context is automatically added to event metadata if none is present.
The default context consists of a tuple with the event prefix and a monotonically increasing integer, e.g. `{EventPrefix, 1}`. If the consumer needs something more unique, this value can be combined with other data at the time of execution for storage in something like ets, e.g. `{pid(), {EventPrefix, 1}}`.
Closes #74

Add support for span context

---

.github/workflows/test.yml

Test with OTP 24 and update patch version numbers for older releases.

Update Erlang on CI

---

doc/overview.edoc
docs.exs
docs.sh
rebar.config
src/telemetry.erl

Our Erlang integration in ExDoc is still in progress, see https://github.com/elixir-lang/ex_doc/issues/1333, but I think it is good enough to generate docs for Telemetry. If you find any bugs please feel free to comment here or on that issue.
Demo: http://wojtekmach.pl/docs/telemetry

Generate docs with ExDoc

---

src/telemetry.erl
test/telemetry_SUITE.erl

This provides immediate feedback for the Telemetry user about improper handler function definition.
I decided to use `info` log level as it is by default disabled in Erlang (default verbosity level is `notice`) so it shouldn't really bother people in production environments (as long as they use Erlang, as Elixir changes default to `debug`).

Inform user about usage of local functions as handlers

---

CHANGELOG.md
README.md
docs.sh

The new version of rebar3 handles dependency versions with an `or` (see https://github.com/erlang/rebar3/pull/2370), so dependencies relying on telemetry will be able to use `~> 0.4 or ~> 1.0`. 
(cc'ing @tsloughter to make sure that I haven't got ☝️ wrong, but it seems to be working with rebar3 3.14.4 in my tests).
We can safely mark 1.0.0 now!
Closes #69

Release 1.0.0

---

src/telemetry.app.src

It is ok to keep `{vsn, "git"}`. I accidentally committed when trying to
publish docs.
For posterity, when publishing docs, don't do it from the main branch.
Do it from the tag. Then it seems to work ok.
See https://github.com/erlef/rebar3_hex/issues/252
Sorry for noise!

Revert vsn change

---

README.md
src/telemetry.erl
test/telemetry_SUITE.erl

We did not add this originally because we said we were waiting for a use case. Well, the use case has arrived: we are using telemetry events to measure the idle time (the time between the last stop and the next start event). :) This helps us do that without recomputing the monotonic times. In terms of costs, the added costs here are negligent (1 word extra in the map values tuple).

Add monotonic_time to span measurements

---

src/telemetry.app.src

Hex.pm recommends this, and it helps tools identify exactly which license this project is released under.

Use SPDX ID for licenses in mixfile

---

RELEASE.md
src/telemetry.app.src

- Adds a link to the hex plugin.
- Adds mix.exs to the extra files that must be included in the published package (1.1.0 already shipped with this).

Post 1.1.0 updates

---

README.md

Hi! This fixes a link that pointed to an archived repo. It now points to where it should. Hope this helps, thanks for your work!

Fix archived link

---

src/telemetry.erl

In response to [Jose's clarification](https://github.com/beam-telemetry/telemetry/issues/112#issuecomment-1289632562), this PR is an attempt to add some additional guidance to the documentation about `span/3`.

Update documentation on telemetry:span/3

---

src/telemetry_test.erl
test/telemetry_test_SUITE.erl

Hey friends!
I find myself doing this constantly. I think it would be good to have something built-in just for the sake of inviting people to test their telemetry events 😄 
I threw a PR together since I thought it'd be easier to talk about something concrete, but I’m not attached to API or implementation here.
Thoughts?

Add telemetry_test

---

src/telemetry_test.erl

👋 When using telemetry_test in an Elixir project we noticed a good amount of test noise from the use of a local function capture. You can reproduce the noise with the following iex session:
```
iex(1)> Mix.install([:telemetry])
Resolving Hex dependencies...
Dependency resolution completed:
New:
telemetry 1.2.0
* Getting telemetry (Hex package)
===> Analyzing applications...
===> Compiling telemetry
:ok
iex(2)> :telemetry_test.attach_event_handlers(self(), [[:foo, :bar]])
21:57:50.835 [info]  The function passed as a handler with ID #Reference<0.3695714495.3782213633.90238> is a local function.
This means that it is either an anonymous function or a capture of a function without a module specified. That may cause a performance penalty when calling that handler. For more details see the …
```

replace local function capture in telemetry_test

---

src/telemetry.erl
test/telemetry_SUITE.erl

This is useful in the case you want all the convenience of `span/3`, but want to return extra measurements, such as the number of bytes in an HTTP request. This is supported by allowing a 3 element version of `SpanFunction`, where the third element is a map of extra measurements. These measurements cannot override the automatic measurements, to prevent mistakes by the user.

Ability to return extra measurements from :telemetry.span

---

rebar.config
src/telemetry.erl
src/telemetry.hrl
src/telemetry_test.erl

Went ahead with this! It looks gorgeous 😉 
Closes #133.

Move docs to OTP 27 ex_doc support

---

CHANGELOG.md
README.md
rebar.config
src/telemetry.app.src
src/telemetry.erl

It's already published to Hex and Hexdocs: http://hexdocs.pm/telemetry

Release v1.3.0

---

src/telemetry.erl

These were not really documented and required digging through source code 🙃

Improve docs for failure events
